package com.redpred.livingsystem.domain.treatment;

/**
 * 治疗结果允许执行的预定义安全操作类型（见开发文档 §13.16）。
 *
 * <p>数据文件只能引用这些预注册操作，不得通过任意字段路径或反射直接修改玩家健康数据。</p>
 */
public enum TreatmentOperationType {
    REDUCE_EXTERNAL_BLEEDING,
    REDUCE_INTERNAL_BLEEDING,
    INCREASE_CLOT_PROGRESS,
    REDUCE_CONTAMINATION,
    REMOVE_FOREIGN_BODY,
    APPLY_WOUND_CLOSURE,
    STABILIZE_FRACTURE,
    REDUCE_FRACTURE_DISPLACEMENT,
    REDUCE_AIR_LEAK,
    REDUCE_AIRWAY_OBSTRUCTION,
    REDUCE_LUNG_FLUID_LOAD,
    RESTORE_BLOOD_VOLUME,
    RESTORE_BODY_FLUID,
    REDUCE_TOXIN_LOAD,
    MODIFY_PATHOGEN_REPLICATION,
    REDUCE_RADIATION_CONTAMINATION,
    APPLY_ANALGESIA,
    APPLY_MEDICATION_EFFECT,
    MODIFY_HEALING_RATE
}
